[package]
name = "AOC"
version = "0.1.0"
edition = "2021"

[dependencies]
regex = "1.11.1"

[profile.release]
debug = true

[[bin]]
name = "dayone"
path = "src/dayone.rs"

[[bin]]
name = "daytwo"
path = "src/daytwo.rs"

[[bin]]
name = "daythree"
path = "src/daythree.rs"
